/**
 * NASHE — youth sports talent discovery platform
 * Brand system: clean white surfaces with a soft light-purple (violet)
 * accent. Primary actions use a modern violet; backgrounds stay airy and
 * white-first, with lavender tints for secondary surfaces. Dark mode keeps
 * the violet identity on deep neutral surfaces.
 */
const colors = {
  light: {
    text: '#1E1B2E',
    tint: '#7C6CF0',
    background: '#FFFFFF',
    foreground: '#1E1B2E',
    card: '#FFFFFF',
    cardForeground: '#1E1B2E',
    primary: '#7C6CF0',
    primaryLight: '#EFECFE',
    primaryForeground: '#FFFFFF',
    secondary: '#F3F1FD',
    secondaryForeground: '#5B4BD5',
    muted: '#F5F4FA',
    mutedForeground: '#6E6A85',
    accent: '#B7A8F8',
    accentForeground: '#2A2350',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E8E5F5',
    input: '#F8F7FD',
    greenHeader: '#7C6CF0',
    greenDark: '#5B4BD5',
    gradientStart: '#8F7FF5',
    gradientEnd: '#6C5AE0',
    male: '#2563EB',
    maleLight: '#E9EFFD',
    female: '#DB2777',
    femaleLight: '#FCE7F3',
    admin: '#5B4BD5',
    scout: '#0369A1',
    success: '#16A34A',
    warning: '#F59E0B',
    like: '#FF4D67',
    likeLight: '#FFE7EB',
  },
  dark: {
    text: '#EDEBF7',
    tint: '#A79BF7',
    background: '#131120',
    foreground: '#EDEBF7',
    card: '#1B1830',
    cardForeground: '#EDEBF7',
    primary: '#A79BF7',
    primaryLight: '#2A2450',
    primaryForeground: '#14102A',
    secondary: '#242046',
    secondaryForeground: '#CFC7FB',
    muted: '#201D38',
    mutedForeground: '#9B95B5',
    accent: '#8F7FF5',
    accentForeground: '#FFFFFF',
    destructive: '#F87171',
    destructiveForeground: '#FFFFFF',
    border: '#2C2850',
    input: '#242046',
    greenHeader: '#181430',
    greenDark: '#100D22',
    gradientStart: '#4A3DA8',
    gradientEnd: '#131120',
    male: '#60A5FA',
    maleLight: '#182B44',
    female: '#F472B6',
    femaleLight: '#341826',
    admin: '#A79BF7',
    scout: '#38BDF8',
    success: '#4ADE80',
    warning: '#FBBF24',
    like: '#FF6B81',
    likeLight: '#3A1620',
  },
  radius: 16,
};

export default colors;
